# Generated by Django 5.0.7 on 2024-09-11 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_catering_equipments_alter_eventcategory_event_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="transaction_id",
        ),
    ]
