# Generated by Django 5.0.7 on 2024-09-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_payment_attendee_alter_payment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='reviewed_at',
        ),
    ]
