# Generated by Django 5.0.7 on 2024-09-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_vendor_event_event_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_fee',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
