# Generated by Django 5.0.7 on 2024-09-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_vendor_vendor_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='catering_fee',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
