# Generated by Django 5.0.7 on 2024-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_catering_catering_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='equipment_fee',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
