# Generated by Django 5.0.7 on 2024-09-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_equipments_equipment_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='equipment_fee',
        ),
    ]
