# Generated by Django 5.0.7 on 2024-09-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_remove_equipments_equipment_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcategory",
            name="event_name",
            field=models.CharField(
                choices=[
                    ("Conference", "CONFERENCE"),
                    ("Wedding", "WEDDING"),
                    ("Party", "PARTY"),
                    ("Reception", "RECEPTION"),
                    ("Concert", "CONCERT"),
                    ("Other", "OTHER"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
