# Generated by Django 5.0.4 on 2024-09-23 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0016_attendee_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="event",
        ),
    ]
