# Generated by Django 5.0.4 on 2024-09-23 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0017_remove_ticket_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="event.event",
            ),
            preserve_default=False,
        ),
    ]
