# Generated by Django 5.0.7 on 2024-08-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EVENT_PLANNER', 'Event Planner'), ('VENDOR', 'Vendor'), ('CLIENT', 'Client')], default='ADMIN', max_length=20),
        ),
    ]
